spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: UserService
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        - id: CartService
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**

        - id: ProductService
          uri: http://localhost:8084
          predicates:
            - Path=/api/product/**
        - id: OrderService
          uri: http://localhost:8085
          predicates:
            - Path=/api/order/**
        - id: CatcheService
          uri: http://localhost:8086
