name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: This will install Java JDK 17 and Maven.
        run: | 
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          sudo apt install maven -y

      - name: This will give version of packages which have install
        run: | 
          java -version
          mvn -version
      
      - name: This will execute and run the packages.
        run: mvn clean package
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./UserService
          file: ./UserService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kttk-ck:latest
